version: '3.8'

volumes:
  postgres_data: {}

networks:
  curramba_network:
    name: curramba_network
    driver: bridge

services:

  ##########################################
  # Postgres: The database used by Keycloak
  ##########################################
  keycloak-database:
    image: postgres:${POSTGRES_TAG}
    container_name: keycloak-database
    volumes:
      - postgres_data:${POSTGRES_TARGET_DATA_VOLUME}
    restart: always
    networks:
      - curramba_network
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USERNAME}      
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - $POSTGRES_PORT:5432

  #######################################
  # Keycloak: The IAM
  #######################################
  keycloak:
    image: quay.io/keycloak/keycloak:${KC_TAG}
    container_name: keycloak
    restart: unless-stopped
    environment:
      KC_DB: ${KC_DATABASE}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_SCHEMA: ${KC_DB_SCHEMA}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KEYCLOAK_ADMIN: ${KC_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HTTP_RELATIVE_PATH: ${KC_HTTP_RELATIVE_PATH}
      KC_PROXY: ${KC_PROXY}
      #KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED}
      #KC_METRICS_ENABLED: ${KC_METRICS_ENABLED}
    networks:
      - curramba_network
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - keycloak-database
    command: ["start"]

  #######################################
  # Nginx: The Reverse Proxy
  #######################################  
  keycloak-proxy:
    image: nginx:latest
    container_name: keycloak-proxy
    networks:
      - curramba_network
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${NGINX_VOLUME_CONF}nginx.conf:/etc/nginx/nginx.conf:rw
      - ${NGINX_VOLUME_CONF}:/usr/local/conf.d:rw
      - ${NGINX_VOLUME_TLS}:/usr/local/tls:rw
    restart: on-failure
    depends_on:
      - keycloak